### ISSUE TITLE
Feature request - `undefined` fields using the "optional parameter" `?` syntax

### ISSUE THREAD

**Issue by RossRogers** [Wulf/tsync#3]
Thanks for this fantastic library!

Typescript has the ["Optional parameters"](https://www.typescriptlang.org/docs/handbook/2/functions.html#optional-parameters) syntax for fields that implicitly add the `undefined` type to a field. 

Instead of 
```typescript
interface Foo {
  id: number,
  bar: string|undefined
}
```
you can do the following:
```typescript
interface Foo {
  id: number,
  bar?: string
}
```

`bar` in the second case is still of type `string|undefined`, but then it is possible to omit field `bar` from instances completely and typescript will not error out.

Instead of explicitly creating a `Foo` like:

```typescript
let foo: Foo = {
  id: 42
  bar: undefined
}
```

You can do:
```typescript
let foo: Foo = {
  id: 42
}
```

Is this a possibility?  Or perhaps a possible run flag?

**Comment by Wulf** [comment]
hey @RossRogers, thanks for reporting this! I'd definitely prefer omitting the key entirely! 

Do you mind creating a PR for this? I think we should modify the return type of [`to_typescript_type`](https://github.com/Wulf/tsync/blob/main/src/main.rs#L67) to a struct which returns the String as well as whether or not it's optional.

Then when we call `to_typescript_type`, we can use the returned data about whether it's optional or not to render the file differently [here](https://github.com/Wulf/tsync/blob/main/src/main.rs#L257) (i.e. rendering `field_name?: field_type` instead of `| undefined`.
